// 엄마랑 후쿠오카 2박 3일 일정 데이터
// tag: normal | food | onsen | shop  (워시테이프 색상에 사용)

const TRIP = {
  title: "엄마랑 후쿠오카 2박 3일",
  hotel: "프린스 스마트인 하카타 (하카타역 도보 5분)",
  // 마이맵 embed 링크 - 여기 값을 바꾸면 모든 기기(폰/아이패드/동행자)에서 동일하게 보임
  mapEmbedUrl: "https://www.google.com/maps/d/embed?mid=1HCObB6k8sQUzeuHVu9o_LDUuGEkl29M&ehbc=2E312F&noprof=1",
  flights: [
    {
      route: "부산김해 → 후쿠오카",
      date: "2026-08-02 (일)",
      dep: "13:05 부산김해공항",
      arr: "14:05 후쿠오카공항",
      code: "7C1453"
    },
    {
      route: "후쿠오카 → 부산김해",
      date: "2026-08-04 (화)",
      dep: "14:55 후쿠오카공항",
      arr: "16:00 부산김해공항",
      code: "7C1454"
    }
  ]
};

const ITEMS = [
  // ---------------- DAY 1 : 2026-08-02(일) ----------------
  { id: "d1-1", day: 1, time: "13:05", tag: "normal",
    title: "부산김해공항 출발 (7C1453)",
    desc: "부산 → 후쿠오카, 예정 도착 14:05",
    mapQuery: "김해국제공항" ,
    remark: "" },
  { id: "d1-2", day: 1, time: "14:05", tag: "normal",
    title: "후쿠오카 공항 도착",
    desc: "입국수속 & 하카타역 이동 (약 20분)",
    mapQuery: "후쿠오카 공항 국제선터미널" ,
    remark: "" },
  { id: "d1-3", day: 1, time: "15:00", tag: "normal",
    title: "호텔 체크인",
    desc: "프린스 스마트인 하카타",
    mapQuery: "프린스 스마트인 하카타" ,
    remark: "" },
  { id: "d1-4", day: 1, time: "15:30", tag: "food",
    title: "카페 · 신발 벗고 편안하게",
    desc: "일본 감성 가득한 다다미 카페에서 여유 타임",
    mapQuery: "하카타 카페" ,
    remark: "" },
  { id: "d1-5", day: 1, time: "16:30", tag: "shop",
    title: "캐널시티 하카타",
    desc: "분수쇼 & 쇼핑 & 산책",
    mapQuery: "캐널시티 하카타" ,
    remark: "" },
  { id: "d1-6", day: 1, time: "18:30", tag: "food",
    title: "저녁 - 요시즈카 우나기야",
    desc: "장어덮밥 맛집 (캐널시티 뒤쪽)",
    mapQuery: "요시즈카 우나기야 캐널시티" ,
    remark: "" },
  { id: "d1-7", day: 1, time: "20:00", tag: "shop",
    title: "돈키호테 하카타점",
    desc: "쇼핑 천국! 기념품 구경",
    mapQuery: "돈키호테 하카타점" ,
    remark: "" },
  { id: "d1-8", day: 1, time: "21:00", tag: "normal",
    title: "나카스 강변 산책",
    desc: "야경이 예뻐요",
    mapQuery: "나카스 강변 후쿠오카" ,
    remark: "" },
  { id: "d1-9", day: 1, time: "21:30", tag: "normal",
    title: "호텔 복귀 & 휴식",
    desc: "",
    mapQuery: "프린스 스마트인 하카타" ,
    remark: "" },

  // ---------------- DAY 2 : 2026-08-03(월) ----------------
  { id: "d2-1", day: 2, time: "09:00", tag: "normal",
    title: "호텔 출발",
    desc: "",
    mapQuery: "프린스 스마트인 하카타" ,
    remark: "" },
  { id: "d2-2", day: 2, time: "09:30", tag: "normal",
    title: "스미요시 신사",
    desc: "조용하고 아름다운 신사",
    mapQuery: "스미요시 신사 후쿠오카" ,
    remark: "" },
  { id: "d2-3", day: 2, time: "10:30", tag: "normal",
    title: "라쿠스이엔",
    desc: "일본 정원 산책 & 말차 타임",
    mapQuery: "라쿠스이엔 후쿠오카" ,
    remark: "" },
  { id: "d2-4", day: 2, time: "12:00", tag: "normal",
    title: "텐진 이동",
    desc: "지하철로 약 5분",
    mapQuery: "텐진역" ,
    remark: "" },
  { id: "d2-5", day: 2, time: "13:00", tag: "food",
    title: "점심 - 키와미야 함바그 (PARCO)",
    desc: "텐진 파르코 8F, 육즙 가득 함바그 맛집",
    mapQuery: "키와미야 함바그 텐진 파르코" ,
    remark: "" },
  { id: "d2-6", day: 2, time: "14:30", tag: "shop",
    title: "텐진 쇼핑 & 산책",
    desc: "파르코, 이와타야, 텐진 지하상가 등",
    mapQuery: "텐진 지하상가" ,
    remark: "고구마스틱 1층" },
  { id: "d2-7", day: 2, time: "16:30", tag: "normal",
    title: "오호리공원 산책",
    desc: "호수 둘레길 산책, 보트 대여 가능",
    mapQuery: "오호리공원" ,
    remark: "" },
  { id: "d2-8", day: 2, time: "19:00", tag: "food",
    title: "저녁 - 원조 모츠나베 라쿠텐지",
    desc: "숙소 바로 뒤! 진한 국물 모츠나베",
    mapQuery: "원조 모츠나베 라쿠텐지" ,
    remark: "" },
  { id: "d2-9", day: 2, time: "20:30", tag: "normal",
    title: "호텔 복귀 & 휴식",
    desc: "",
    mapQuery: "프린스 스마트인 하카타" ,
    remark: "" },

  // ---------------- DAY 3 : 2026-08-04(화) ----------------
  { id: "d3-1", day: 3, time: "08:30", tag: "normal",
    title: "호텔 체크아웃 & 짐 보관",
    desc: "하카타역 짐 보관 이용 (유료)",
    mapQuery: "하카타역 코인로커" ,
    remark: "" },
  { id: "d3-2", day: 3, time: "09:00", tag: "food",
    title: "REC COFFEE 하카타마루이점",
    desc: "바리스타 챔피언 라떼 맛보기",
    mapQuery: "REC COFFEE 하카타마루이" ,
    remark: "" },
  { id: "d3-3", day: 3, time: "10:00", tag: "shop",
    title: "아뮤플라자 하카타 & 한큐백화점",
    desc: "기념품 쇼핑",
    mapQuery: "아뮤플라자 하카타" ,
    remark: "" },
  { id: "d3-4", day: 3, time: "12:00", tag: "food",
    title: "점심 - 스시사카바 사시스킷테 하카타점",
    desc: "하카타역 에키니아쿠 1F",
    mapQuery: "스시사카바 사시스킷테 하카타점" ,
    remark: "" },
  { id: "d3-5", day: 3, time: "13:30", tag: "normal",
    title: "하카타역 → 공항 이동",
    desc: "약 10분",
    mapQuery: "후쿠오카 공항" ,
    remark: "" },
  { id: "d3-6", day: 3, time: "14:55", tag: "normal",
    title: "후쿠오카공항 출발 (7C1454)",
    desc: "예정 도착 16:00 김해공항",
    mapQuery: "후쿠오카 공항 국제선터미널" ,
    remark: "" },
];

// 체크리스트 탭 "참고정보" 섹션에 노출되는 항목 (탭하면 고정 카드 팝업이 열림)
const REFERENCE_ITEMS = [
  { id: "ref-airport-station", title: "공항 ↔ 하카타역 이동방법" },
];
